service: banao-hms-email-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev

functions:
  sendEmail:
    handler: handler.send_notification
    events:
      - http:
          path: notify
          method: post
          cors: true

plugins:
  - serverless-offline # Allows you to run 'sls offline' for local development
